Repository LAION-AI/Open-Assistant, pull requests merged in 2023-08, with the labels that each got.

#3618 Add rope-scaling parameters to export_model.py
  model/model_training/tools/export_model.py
Labels: ml

#3632 Web App Manifest - Save as desktop or mobile app
  website/public/images/logos/logo_192x192.png
  website/public/manifest.json
  website/src/pages/_document.tsx
Labels: website

#3651 Make sure eval subset is sampled without replacing
  model/model_training/custom_datasets/__init__.py
Labels: ml

#3650 Add loader for megacode2 (rombodawg/LosslessMegaCodeTrainingV2_1m_Evol_Uncensored)
  model/model_training/custom_datasets/instruction.py
Labels: ml

#3654 Add pretokenizer utility
  model/pretokenizer/README.md
  model/pretokenizer/configs/pretokenize.yaml
  model/pretokenizer/create_hf_tokenizer_config.py
  model/pretokenizer/indexed_dataset.py
  model/pretokenizer/pretokenize.py
  model/pretokenizer/requirements.txt
  model/pretokenizer/tokenizer.py
Labels: ml

#3668 Support ChatML prompt format in worker
  inference/worker/chat_chain.py
  inference/worker/chat_chain_prompts.py
  inference/worker/chat_chain_utils.py
  inference/worker/settings.py
  inference/worker/utils.py
  inference/worker/work.py
  oasst-shared/oasst_shared/model_configs.py
Labels: inference

#3614 [Fix] Consume much more gpt memory running eval_rm
  model/model_eval/eval_rm.py
  model/model_training/custom_datasets/__init__.py
  model/model_training/custom_datasets/qa_datasets.py
Labels: ml
